//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.ConsoleApp.ConsoleResource", typeof(ConsoleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account number must be numeric.
        /// </summary>
        internal static string AccountNumberNumericOnly {
            get {
                return ResourceManager.GetString("AccountNumberNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance : {0}.
        /// </summary>
        internal static string BalanceTotal {
            get {
                return ResourceManager.GetString("BalanceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Consult your transactions, type &quot;(C)onsult&quot;.
        /// </summary>
        internal static string Consult {
            get {
                return ResourceManager.GetString("Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your deposit of {0} has been registered.
        /// </summary>
        internal static string DepositRegistered {
            get {
                return ResourceManager.GetString("DepositRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à end.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter an amount or Exit to exit.
        /// </summary>
        internal static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a date of {0} in the format &quot;dd/MM/yyyy&quot; or Exit to exit.
        /// </summary>
        internal static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occured we apologize for the inconvenience..
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you for using our services, see you soon..
        /// </summary>
        internal static string GoodBye {
            get {
                return ResourceManager.GetString("GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The entered date is incorrect.
        /// </summary>
        internal static string IncorrectDateEntry {
            get {
                return ResourceManager.GetString("IncorrectDateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Make a deposit, type &quot;(D)eposit&quot;.
        /// </summary>
        internal static string MakeDeposit {
            get {
                return ResourceManager.GetString("MakeDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Make a withdrawal, type &quot;(W)ithdrawal&quot;.
        /// </summary>
        internal static string MakeWithdrawal {
            get {
                return ResourceManager.GetString("MakeWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Or type &quot;Exit&quot; to exit.
        /// </summary>
        internal static string OrTypeExit {
            get {
                return ResourceManager.GetString("OrTypeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount must be a positive number.
        /// </summary>
        internal static string PositiveAmountOnly {
            get {
                return ResourceManager.GetString("PositiveAmountOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The amount must be a positive comma separated number.
        /// </summary>
        internal static string PositiveCommaSeparatedAmountOnly {
            get {
                return ResourceManager.GetString("PositiveCommaSeparatedAmountOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue.
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select an operation :.
        /// </summary>
        internal static string SelectOperation {
            get {
                return ResourceManager.GetString("SelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your account number or type &quot;(E)xit&quot; to exit.
        /// </summary>
        internal static string TypeAccountNumber {
            get {
                return ResourceManager.GetString("TypeAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command {0} was not recognized..
        /// </summary>
        internal static string UnrecognizedCommand {
            get {
                return ResourceManager.GetString("UnrecognizedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your withdrawal of {0} has been registered.
        /// </summary>
        internal static string WithdrawalRegistered {
            get {
                return ResourceManager.GetString("WithdrawalRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your transactions :.
        /// </summary>
        internal static string YourTransactions {
            get {
                return ResourceManager.GetString("YourTransactions", resourceCulture);
            }
        }
    }
}
